"""SPEC-02 — config, project discovery, dialect resolution."""

from .config import (
    AdapterConfigYaml,
    BaselineConfig,
    ComplexityConfig,
    CoverageConfig,
    CoverageExemptions,
    CoverageThreshold,
    DbtcovConfig,
    GateConfig,
    GateThresholds,
    OverrideEntry,
    RenderConfig,
    ReportsConfig,
    RuleOverride,
    SkipsThresholds,
    TestingConfig,
    TestingThresholds,
    TestOverrides,
    WeightTable,
    load_config,
    write_default_config,
)
from .dialect import ADAPTER_TO_SQLGLOT_DIALECT, resolve_dialect
from .project_discovery import DbtProjectInfo, find_project_root, load_project_info

__all__ = [
    "DbtProjectInfo",
    "find_project_root",
    "load_project_info",
    "DbtcovConfig",
    "RenderConfig",
    "RuleOverride",
    "CoverageThreshold",
    "CoverageConfig",
    "ComplexityConfig",
    "AdapterConfigYaml",
    "WeightTable",
    "TestOverrides",
    "BaselineConfig",
    "GateConfig",
    "GateThresholds",
    "OverrideEntry",
    "CoverageExemptions",
    "ReportsConfig",
    "SkipsThresholds",
    "TestingConfig",
    "TestingThresholds",
    "load_config",
    "write_default_config",
    "ADAPTER_TO_SQLGLOT_DIALECT",
    "resolve_dialect",
]
